### ISSUE TITLE
array_copy does not work in cpp

### ISSUE THREAD

**Issue by felipeek** [Hoshoyo/hutils#1]
In file included from src/obj.cpp:5:
src/obj.cpp: In function ‘void randomize(Vertex*, u32*)’:
include/light_array.h:149:33: error: ‘array_dyn_allocate_capacity’ was not declared in this scope
  149 |     memmove((Dynamic_ArrayBase*)array_dyn_allocate_capacity(sizeof(*A), array_capacity(A)) - 1, \
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/obj.cpp:167:26: note: in expansion of macro ‘array_copy’
  167 |  Vertex* vertices_copy = array_copy(vertices);
      |                          ^~~~~~~~~~
make: *** [Makefile:36: bin/obj/obj.o] Error 1

**Comment by Hoshoyo** [comment]
Fixed in 680cd576207b33b3ed8d5187284bee802fd80f10
